### ISSUE TITLE
Hello World em python funciona apenas na versão do python 3.0 ou superior

### ISSUE THREAD

**Issue by jaafreitas** [luz-sf/teste-git#6]
Deveríamos dar suporte a versão do python 2.7

**Comment by jaafreitas** [comment]
Segue evidências que estou utilizando a versão 3.3.2 do python

![python3 3 2](https://cloud.githubusercontent.com/assets/885458/9315288/c888fd94-4504-11e5-96bc-65a9edb6b580.png)

Agradeceria urgência na solução deste problema.

**Comment by jaafreitas** [comment]
@leandro-lef, pode confirmar que isso é um bug?

**Comment by jaafreitas** [comment]
Verificar dependência com #7

**Comment by jaafreitas** [comment]
@VictorSFaria, você recebeu esta notificação por email? Se sim, talvez não seja uma boa ideia usar contas de email pessoal.

**Comment by jaafreitas** [comment]
@VictorSFaria, eles pensaram em tudo mesmo...

_Personal settings -> Notification center:_
_Custom routing_
_You can send notifications to different verified email addresses depending on the organization that owns the repository._

**Comment by jaafreitas** [comment]
Seria legal o time @luz-sf/gerencial verificar também.

**Comment by leandro-lef** [comment]
Comecei a receber a partir da mensagem linkando com o ítem #7...

Mas no preview da mensagem mostra o texto da mensagem anterior, embora eu
não a encontre na minha caixa de e-mail.

Gmail me enrolando....

Atenciosamente,

_Leandro Augusto Soares_
leandro@luz-ef.com

_Tel.:_ 55 (16) 3374-9742

2015-08-17 19:57 GMT-03:00 Adriano notifications@github.com:

**Comment by jaafreitas** [comment]
@leandro-lef, a sua resposta via email também vem para o histórico. Podemos pensar em algo mais integrado para as demais áreas.

**Comment by leandro-lef** [comment]
@jaafreitas, sim, eu quis testar o envio da resposta por e-mail mesmo.

Será que rola algum integração com o zendesk?

**Comment by leandro-lef** [comment]
@jaafreitas, dá uma olhada

https://github.com/jaafreitas?tab=activity

**Comment by jaafreitas** [comment]
Acho bem provável!

  Talvez o @VictorSFaria tenha visto algo nessa linha.

On Mon, Aug 17, 2015 at 8:04 PM, leandro-lef notifications@github.com
wrote:

> @jaafreitas https://github.com/jaafreitas, sim, eu quis testar o envio
> da resposta por e-mail mesmo.
> 
> Será que rola algum integração com o zendesk?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/luz-sf/teste-git/issues/6#issuecomment-131988006.

## 

_Adriano Freitas_
adriano@luz-ef.com

_Tel.:_ 55 (11) 3799-4700

**Comment by jaafreitas** [comment]
@leandro-lef , estou ciente. Tudo o que é publico aparece lá.
https://github.com/leandro-lef?tab=activity
