### ISSUE TITLE
Hello World com suporte a internacionalização

### ISSUE THREAD

**Issue by jaafreitas** [luz-sf/teste-git#7]
# Objetivo

Precisamos de suporte a outros idiomas além do inglês.
Veja que temos que dar suporte a outras linguagens de programação devido aos requisitos #4, #5.
## Exemplos
- Inglês: "Hello, World"
- Português: "Olá, Mundo"

**Comment by jaafreitas** [comment]
Eu acho que essa feature está com a documentação fraca.
Para um bom exemplo de documentação, favor verificar #5

**Comment by VictorSFaria** [comment]
Algumas dúvidas:
Será parametrizado? 
Olhará o padrão do sistema?
